# /// script
# dependencies = [
#   "pandas>=2.0",
#   "pyarrow>=15",
#   "numpy>=1.26",
#   "matplotlib>=3.8",
# ]
# ///
"""Render paper figures + LaTeX tables from ``data/perf.parquet``.

Produces, under ``figures/`` and ``tables/``:

* ``train_vs_val_ratio.{pdf,png}`` — two-panel grouped bar chart of
  per-step wall-time **relative to the vanilla DiGress (vignac) baseline**,
  train panel vs validation panel, grouped by dataset. A dashed line marks
  parity (1.0); bars below it are faster than vanilla.
* ``perf_summary.tex`` — booktabs table with absolute train-step and
  per-val-cycle times plus the ratio and %-change vs vignac.

The narrative the figure supports: the projection/feature variants cost a
little (or break even) at *training* time but several recover or exceed
parity at *validation* time, with ``pearl-gnnconv-norm`` the clearest
validation win on both datasets. See ``README.md`` for the derivation
caveats on the validation-time number.

Run from repo root:  uv run paper-artifacts/pearl-perf/render.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
PARQUET = HERE / "data" / "perf.parquet"
FIG_DIR = HERE / "figures"
TAB_DIR = HERE / "tables"

# Display order + pretty labels. Baseline first.
VARIANT_ORDER = ["vignac", "pearl", "pearl-spectral", "pearl-gnnconv-norm"]
VARIANT_LABEL = {
    "vignac": "DiGress\n(eigh)",
    "pearl": "PEARL",
    "pearl-spectral": "PEARL +\nspectral Q/K/V",
    "pearl-gnnconv-norm": "PEARL +\nGNN Q/K/V",
}
DATASET_ORDER = ["sbm", "enzymes"]
DATASET_LABEL = {"sbm": "SBM ($n_{\\max}{=}200$)", "enzymes": "ENZYMES ($n_{\\max}{=}126$)"}
# Colourblind-safe (Wong) palette.
DATASET_COLOR = {"sbm": "#0072B2", "enzymes": "#D55E00"}

plt.rcParams.update(
    {
        "font.family": "serif",
        "font.size": 9,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "legend.fontsize": 8,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "figure.dpi": 150,
        "savefig.bbox": "tight",
    }
)


def _pct(ratio: float) -> float:
    """Signed % change vs baseline; negative = faster than vanilla."""
    return (ratio - 1.0) * 100.0


def render_figure(df: pd.DataFrame) -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0), sharey=True)

    panels = [
        ("train_ratio_vs_vignac", "Training step", axes[0]),
        ("val_ratio_vs_vignac", "Validation cycle", axes[1]),
    ]
    # Non-baseline variants only (baseline is the 1.0 reference line).
    variants = [v for v in VARIANT_ORDER if v != "vignac"]
    x = np.arange(len(variants))
    width = 0.38

    for col, title, ax in panels:
        for i, ds in enumerate(DATASET_ORDER):
            sub = df[df["dataset"] == ds].set_index("variant")
            ratios = [sub.loc[v, col] for v in variants]
            offs = (i - 0.5) * width
            bars = ax.bar(
                x + offs,
                ratios,
                width,
                label=DATASET_LABEL[ds],
                color=DATASET_COLOR[ds],
                edgecolor="black",
                linewidth=0.4,
            )
            for rect, r in zip(bars, ratios):
                ax.annotate(
                    f"{_pct(r):+.0f}%",
                    (rect.get_x() + rect.get_width() / 2, r),
                    ha="center",
                    va="bottom" if r >= 1 else "top",
                    fontsize=6.5,
                    xytext=(0, 2 if r >= 1 else -2),
                    textcoords="offset points",
                )
        ax.axhline(1.0, color="black", lw=0.9, ls="--", zorder=0)
        ax.set_title(title)
        ax.set_xticks(x)
        ax.set_xticklabels([VARIANT_LABEL[v] for v in variants])
        ax.set_ylim(0.7, 1.85)
        ax.grid(axis="y", lw=0.3, alpha=0.5)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)

    axes[0].set_ylabel("wall time / vanilla DiGress")
    # Shared legend, annotate the parity line meaning.
    axes[1].legend(loc="upper right", frameon=False)
    axes[0].text(
        0.02, 0.96, "below 1.0 = faster than vanilla",
        transform=axes[0].transAxes, fontsize=6.5, va="top", style="italic", color="0.3",
    )
    fig.suptitle(
        "Per-step wall time relative to vanilla DiGress (lower = better)",
        fontsize=10, y=1.02,
    )
    for ext in ("pdf", "png"):
        fig.savefig(FIG_DIR / f"train_vs_val_ratio.{ext}")
    plt.close(fig)
    print(f"figures -> {FIG_DIR}/train_vs_val_ratio.{{pdf,png}}")


def render_table(df: pd.DataFrame) -> None:
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by paper-artifacts/pearl-perf/render.py — do not edit by hand.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \small",
        r"  \caption{Per-step wall time of feature/projection variants relative to the"
        r" vanilla DiGress baseline (eigh-based \texttt{ExtraFeatures(all)}). Training"
        r" step time is a robust median over the full run history (forward + backward +"
        r" optimizer). Validation-cycle time is wall-clock-derived"
        r" ($\text{runtime} - \text{median train step}\times\text{steps}$, per validation"
        r" cycle) and bundles validation forward, diffusion sampling, MMD and I/O."
        r" Ratios $<1$ (negative \%) are faster than vanilla. Data: 2026-05-06"
        r" \texttt{*\_repro\_exact} runs, A100, $\sim$17.7\,h each.}",
        r"  \label{tab:pearl-perf}",
        r"  \begin{tabular}{llrrrr}",
        r"    \toprule",
        r"    & & \multicolumn{2}{c}{Training step (s)} & \multicolumn{2}{c}{Validation cycle (s)} \\",
        r"    \cmidrule(lr){3-4}\cmidrule(lr){5-6}",
        r"    Dataset & Variant & abs & vs base & abs & vs base \\",
        r"    \midrule",
    ]
    for ds in DATASET_ORDER:
        sub = df[df["dataset"] == ds].set_index("variant")
        lines.append(f"    \\multirow{{4}}{{*}}{{{DATASET_LABEL[ds]}}}")
        for v in VARIANT_ORDER:
            row = sub.loc[v]
            tr_abs = row["train_step_med"]
            va_abs = row["val_per_cycle_s"]
            if v == "vignac":
                tr_rel = va_rel = "---"
            else:
                tr_rel = f"{_pct(row['train_ratio_vs_vignac']):+.0f}\\%"
                va_rel = f"{_pct(row['val_ratio_vs_vignac']):+.0f}\\%"
            label = v.replace("pearl-gnnconv-norm", "PEARL+GNN").replace(
                "pearl-spectral", "PEARL+spec").replace(
                "pearl", "PEARL").replace("vignac", "DiGress (eigh)")
            lines.append(
                f"      & {label} & {tr_abs:.3f} & {tr_rel} & {va_abs:.0f} & {va_rel} \\\\"
            )
        lines.append(r"    \midrule" if ds != DATASET_ORDER[-1] else r"    \bottomrule")
    lines += [r"  \end{tabular}", r"\end{table}", ""]
    out = TAB_DIR / "perf_summary.tex"
    out.write_text("\n".join(lines))
    print(f"table   -> {out}")


def main() -> None:
    df = pd.read_parquet(PARQUET)
    render_figure(df)
    render_table(df)
    # Console summary of the headline numbers.
    print("\n% change vs vanilla DiGress (negative = faster):")
    for ds in DATASET_ORDER:
        sub = df[df["dataset"] == ds].set_index("variant")
        print(f"  {ds}:")
        for v in VARIANT_ORDER:
            if v == "vignac":
                continue
            tr = _pct(sub.loc[v, "train_ratio_vs_vignac"])
            va = _pct(sub.loc[v, "val_ratio_vs_vignac"])
            print(f"    {v:<20} train {tr:+5.0f}%   val {va:+5.0f}%")


if __name__ == "__main__":
    main()
