# Standard GNN model configuration

_target_: tmgg.experiments.gnn_denoising.lightning_module.GNNDenoisingLightningModule

# Model-specific architecture parameters
model_type: "GNN"  # "GNN", "NodeVarGNN", "GNNSymmetric"
num_layers: 1
num_terms: 4
feature_dim_in: 20
feature_dim_out: 20

# Training parameters (inherit from base_config_training.yaml)
learning_rate: ${learning_rate}
loss_type: ${loss_type}
weight_decay: ${weight_decay}
optimizer_type: ${optimizer_type}
scheduler_config:
  type: "cosine_warmup"
  warmup_fraction: 0.02
  decay_fraction: 0.8
rotation_k: 20

# These are overridden by base_config_gnn.yaml
noise_type: ${data.noise_type}
noise_levels: ${data.noise_levels}
seed: ${seed}