# Hybrid model with GNN only (no transformer denoising)
# Extends base lightning configuration

defaults:
  - /base/lightning_base

_target_: tmgg.experiments.hybrid_denoising.lightning_module.HybridDenoisingLightningModule

model_type: hybrid_gnn

# Model-specific architecture parameters
# GNN configuration
gnn_num_layers: 2
gnn_num_terms: 2
gnn_feature_dim_in: 20
gnn_feature_dim_out: 5

# Transformer configuration (disabled)
use_transformer: false
transformer_num_layers: 4
transformer_num_heads: 4
transformer_d_k: 10
transformer_d_v: 10
transformer_dropout: 0.0
transformer_bias: true

# Training parameters (inherit from base_config_training.yaml)
learning_rate: ${learning_rate}
loss_type: ${loss_type}
weight_decay: ${weight_decay}
optimizer_type: ${optimizer_type}