# Hybrid GNN+Transformer model configuration

_target_: tmgg.experiments.hybrid_denoising.lightning_module.HybridDenoisingLightningModule

model_type: hybrid_transformer

# Model-specific architecture parameters
# GNN configuration
gnn_num_layers: 2
gnn_num_terms: 2
gnn_feature_dim_in: 20
gnn_feature_dim_out: 5

# Transformer configuration
use_transformer: true
transformer_num_layers: 4
transformer_num_heads: 4
transformer_d_k: 10
transformer_d_v: 10
transformer_dropout: 0.0
transformer_bias: true

# Training parameters (inherit from base_config_training.yaml)
learning_rate: ${learning_rate}
loss_type: ${loss_type}
weight_decay: ${weight_decay}
optimizer_type: ${optimizer_type}
scheduler_config:
  type: "cosine_warmup"
  warmup_fraction: 0.02
  decay_fraction: 0.8
rotation_k: 20

# These are overridden by base_config_hybrid.yaml
noise_type: ${data.noise_type}
noise_levels: ${data.noise_levels}
seed: ${seed}