# Stage 3: PyG Dataset Evaluation
# Tests both spectral and digress models on real-world PyG datasets
# (enzymes, proteins) to validate generalization beyond synthetic graphs.

name: stage3_pyg
base_config: base_config_spectral

architectures:
  # Spectral variants
  - models/spectral/linear_pe
  - models/spectral/self_attention
  - models/spectral/filter_bank
  # DiGress variants
  - models/digress/digress_transformer
  - models/digress/digress_transformer_gnn_qk

datasets:
  - pyg_enzymes_single_graph
  - pyg_proteins_single_graph

hyperparameters:
  learning_rate: [5e-4, 1e-3]
  weight_decay: [1e-2, 1e-3]
  "+model.k": [16, 32]

seeds: [1, 2, 3]

run_id_template: "stage3_pyg_{arch}_{data}_{lr}_{wd}_{k}_s{seed}"
