# DiGress GraphTransformer with spectral projections for Q and K only
# Uses eigenvalue-polynomial filtering for query/key, linear projection for value

_target_: tmgg.experiments.digress_denoising.lightning_module.DigressDenoisingLightningModule

# Experiment naming
digress_arch: "spectral_qk"
digress_mode: "eigenvec"
model_type: digress_spectral_qk_eigenvec

# Training parameters (inherit from base_config_training.yaml)
learning_rate: ${learning_rate}
loss_type: ${loss_type}
weight_decay: ${weight_decay}
optimizer_type: ${optimizer_type}
scheduler_config:
  type: "cosine_warmup"
  warmup_fraction: 0.02
  decay_fraction: 0.8

# These are overridden by base_config_digress.yaml
noise_type: ${data.noise_type}
noise_levels: ${data.noise_levels}
seed: ${seed}

# Model-specific architecture parameters
use_eigenvectors: true
k: 50
n_layers: 4
hidden_mlp_dims:
  X: 256
  E: 64
  y: 256
hidden_dims:
  dx: 128
  de: 32
  dy: 128
  n_head: 4
  # Spectral projections for Q and K
  use_spectral_q: true
  use_spectral_k: true
  use_spectral_v: false
  spectral_k: 16
  spectral_num_terms: 3

output_dims:
  X: 0
  E: 1
  y: 0
