# @package _global_
# Stage 1 Sanity Check: Constant Noise Memorization
#
# Tests whether models can memorize a fixed noisy→clean mapping.
# Expected: ~99% accuracy after training (if architecture works).
#
# This is a debugging/validation stage, not a benchmark. It verifies:
# 1. Model has sufficient capacity to represent the mapping
# 2. Gradient flow works correctly through all layers
# 3. Optimizer can update weights in the right direction
#
# If this fails, something fundamental is broken.

defaults:
  - override /data: sbm_default

# Stage identifier
stage: stage1_sanity

# Modal cloud execution (off by default, use run_on_modal=true to enable)
run_on_modal: false

# Fixed noise mode: same noisy input every training step
fixed_noise_seed: 42

# Single noise level (no random sampling needed for memorization test)
noise_levels: [0.1]
eval_noise_levels: [0.1]

# Optimizer settings matching successful unit test
learning_rate: 1e-2
weight_decay: 0.0
optimizer_type: adam

# Disable LR scheduling for simpler optimization
scheduler_config:
  type: none

# Full spectrum for n=50 graph
model:
  k: 50

# --- Sweep metadata (used by coordinator when sweep=true) ---
_sweep_config:
  architectures:
    - models/spectral/linear_pe
    - models/spectral/filter_bank
    - models/spectral/self_attention
  hyperparameter_space:
    learning_rate: [1e-2]
    weight_decay: [0.0]
    model.k: [50]  # Full spectrum for n=50 graph
  num_trials: 1
  seeds: [1]
  timeout_seconds: 300
  success_criteria:
    metric: val_accuracy
    threshold: 0.99
