# @package _global_
# Stage 2: Cross-Dataset Validation (unified single-graph and cross-graph protocols)
#
# Budget: ~19 GPU-hours (5 architectures x 9 datasets x 3 noise levels x 3 seeds)
# Goal: Validate denoising across diverse graph families
#
# Two protocols controlled by cross_graph parameter:
# - cross_graph=false (default): Train/val/test use SAME graph (single-graph protocol)
# - cross_graph=true: Train/val/test use DIFFERENT graphs (generalization test)
#
# Spectral models: high LR (1e-2) + amsgrad + tiny weight decay
# DiGress: official settings (LR=0.0002, amsgrad, weight_decay=1e-12)

defaults:
  - override /data: er_single_graph

# Stage identifier
stage: stage2_validation

# Protocol toggle: set cross_graph=true via CLI for cross-graph validation
cross_graph: false

# Modal cloud execution (off by default, use run_on_modal=true to enable)
run_on_modal: false

# Data protocol settings (computed from cross_graph)
data:
  same_graph_all_splits: ${not_:${cross_graph}}
  val_test_seed: ${if_:${cross_graph},100,123}

# Optimizer settings (harmonized across all stages)
learning_rate: 1e-2
weight_decay: 1e-12
optimizer_type: adamw
amsgrad: true
scheduler_config:
  type: none

# Model settings
model:
  k: 50

# Default noise levels (overridden in sweep)
noise_levels: [0.1]
eval_noise_levels: [0.1]

# --- Sweep metadata (used by coordinator when sweep=true) ---
_sweep_config:
  architectures:
    # Spectral models (use stage config: high LR + amsgrad)
    - models/spectral/linear_pe
    - models/spectral/filter_bank
    - models/spectral/self_attention
    # DiGress variants
    - models/digress/digress_sbm_small           # official optimizer
    - models/digress/digress_sbm_small_highlr    # high LR ablation
  datasets:
    # Synthetic graphs
    - data/er_single_graph
    - data/regular_single_graph
    - data/tree_single_graph
    - data/roc_single_graph
    - data/lfr_single_graph
    - data/sbm_single_graph
    # PyG benchmark graphs
    - data/pyg_qm9_single_graph
    - data/pyg_enzymes_single_graph
    - data/pyg_proteins_single_graph
  hyperparameter_space:
    noise_levels:
      - [0.01]
      - [0.1]
      - [0.2]
  num_trials: 4
  seeds: [1, 2, 3]
  timeout_seconds: 600
  success_criteria:
    metric: val_loss
    improvement_threshold: 0.15
