# @package _global_
# Stage 2: Cross-Dataset Validation with Separate Graphs
#
# Identical to stage1_5_crossdata, except:
# - same_graph_all_splits: false (train/val/test use different graphs)
#
# Budget: ~19 GPU-hours (5 architectures x 9 datasets x 3 noise levels x 3 seeds)
# Goal: Validate generalization to unseen graph structures
#
# Spectral models: high LR (1e-2) + amsgrad + tiny weight decay
# DiGress: official settings (LR=0.0002, amsgrad, weight_decay=1e-12)

defaults:
  - override /data: er_single_graph

# Stage 2 protocol: use different graphs for val/test
data:
  same_graph_all_splits: false
  val_test_seed: 100  # val uses 100, test uses 1100

# Stage identifier
stage: stage2_validation

# Spectral models: high LR + amsgrad + tiny weight decay
# DiGress overrides these via its own config
learning_rate: 1e-2
weight_decay: 1e-12
optimizer_type: adamw
amsgrad: true
scheduler_config:
  type: none

# Model settings
model:
  k: 50

# Default noise levels (overridden in sweep)
noise_levels: [0.1]
eval_noise_levels: [0.1]

# --- Sweep metadata (used by coordinator when sweep=true) ---
_sweep_config:
  architectures:
    # Spectral models (use stage config: high LR + amsgrad)
    - models/spectral/linear_pe
    - models/spectral/filter_bank
    - models/spectral/self_attention
    # DiGress variants
    - models/digress/digress_sbm_small           # official optimizer
    - models/digress/digress_sbm_small_highlr    # high LR ablation
  datasets:
    # Synthetic graphs
    - data/er_single_graph
    - data/regular_single_graph
    - data/tree_single_graph
    - data/roc_single_graph
    - data/lfr_single_graph
    - data/sbm_single_graph
    # PyG benchmark graphs
    - data/pyg_qm9_single_graph
    - data/pyg_enzymes_single_graph
    - data/pyg_proteins_single_graph
  hyperparameter_space:
    noise_levels:
      - [0.01]
      - [0.1]
      - [0.2]
  num_trials: 4
  seeds: [1, 2, 3]
  timeout_seconds: 600
  success_criteria:
    metric: val_loss
    improvement_threshold: 0.15
