# Hybrid model with ~4000 parameters
# Total: 3,990 parameters

_target_: tmgg.experiments.hybrid_denoising.lightning_module.HybridDenoisingLightningModule

# Architecture for ~4k parameters
# GNN component
gnn_num_layers: 1
gnn_num_terms: 2
gnn_feature_dim_in: 20  # Must match num_nodes in data config
gnn_feature_dim_out: 20  # Must match num_nodes in data config

# Transformer component
use_transformer: true
transformer_num_layers: 2
transformer_num_heads: 5
transformer_d_k: null  # Will default appropriately
transformer_d_v: null  # Will default appropriately
transformer_dropout: 0.0
transformer_bias: true

# Common parameters
learning_rate: 0.001  # Will be overridden in grid search
loss_type: "BCE"  # Hybrid typically uses BCE
scheduler_config:
  type: "cosine_warmup"
  warmup_fraction: 0.02
  decay_fraction: 0.8
rotation_k: 20

# These will be overridden by data config
noise_type: "gaussian"
noise_levels: [0.05, 0.1, 0.2, 0.3, 0.4]
seed: 42