# GNN model with ~4000 parameters
# Total: 4,005 parameters

_target_: tmgg.experiments.gnn_denoising.lightning_module.GNNDenoisingLightningModule

# Architecture for ~4k parameters
model_type: "GNN"
num_layers: 4
num_terms: 2
feature_dim_in: 20  # Must match num_nodes in data config
feature_dim_out: 20  # Must match num_nodes in data config

# Common parameters
learning_rate: 0.001  # Will be overridden in grid search
loss_type: "MSE"
scheduler_config:
  type: "cosine"
  T_0: 20
  T_mult: 2
rotation_k: 20

# These will be overridden by data config
noise_type: "gaussian"
noise_levels: [0.05, 0.1, 0.2, 0.3, 0.4]
seed: 42