# @package _global_
# Step-based callbacks configuration
# Patience is measured in validation checks, not epochs

callbacks:
  early_stopping:
    monitor: val/loss
    mode: min
    patience: 10              # Validation checks (× val_check_interval = steps until stop)
    min_delta: 1e-4
  checkpoint:
    monitor: val/loss
    mode: min
    save_top_k: 3
    save_last: true
    filename: "model-step={step:06d}-val_loss={val/loss:.4f}"
    auto_insert_metric_name: false  # Required when metric names contain slashes
    every_n_train_steps: null  # Use val_check_interval by default
