# @package _global_

# Default configuration: TensorBoard on S3/Tigris + WandB
# Missing credentials will gracefully skip that logger

logger:
  - tensorboard:
      save_dir: s3://${oc.env:TMGG_S3_BUCKET}/${oc.env:TMGG_S3_PREFIX,""}/tensorboard/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
      name: ${experiment_name}
      version: null
      log_graph: false
      default_hp_metric: false
  - wandb:
      project: tmgg
      name: ${experiment_name}
      tags: []
      save_dir: ${paths.output_dir}
      entity: null
      log_model: false
