# @package _global_

# Default configuration: TensorBoard on S3/Tigris + WandB
# Missing credentials will gracefully skip that logger
#
# Note on remote execution (Modal/Ray):
# This entire logger config is REMOVED during prepare_config_for_remote() because
# it contains ${oc.env:...} interpolations that cannot be resolved at serialization
# time. The worker's create_loggers() reconstructs appropriate loggers based on
# environment variables available at runtime.

logger:
  - tensorboard:
      save_dir: s3://${oc.env:TMGG_S3_BUCKET}/${oc.env:TMGG_S3_PREFIX,""}/tensorboard/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
      name: ${experiment_name}
      version: null
      log_graph: false
      default_hp_metric: false
  - wandb:
      project: tmgg-${oc.select:stage,default}
      name: ${experiment_name}
      tags: []
      save_dir: ${paths.output_dir}
      entity: graph_denoise_team
      log_model: false
